export const initialUsers = [
  {
    _id: "usr_admin_1",
    name: "Dr. Albus Vance",
    email: "admin@smartlib.edu",
    password: "admin123",
    role: "admin",
    department: "Chief Library Administration",
    rollNumber: "LIB-CHIEF-01",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "+1 (555) 019-2834",
    joinedDate: "2023-01-10"
  },
  {
    _id: "usr_student_1",
    name: "Aarav Sharma",
    email: "aarav@student.edu",
    password: "student123",
    role: "student",
    department: "Computer Science & Engineering",
    rollNumber: "21CS1084",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98765 43210",
    year: "3rd Year",
    joinedDate: "2023-08-15"
  },
  {
    _id: "usr_student_2",
    name: "Priya Patel",
    email: "priya@student.edu",
    password: "student123",
    role: "student",
    department: "Data Science & AI",
    rollNumber: "22AI1042",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    phone: "+91 98234 56789",
    year: "2nd Year",
    joinedDate: "2024-01-05"
  }
];

export const initialBooks = [
  {
    _id: "b_1",
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    isbn: "978-0132350884",
    category: "Computer Science",
    subject: "Software Engineering & Architecture",
    totalCopies: 6,
    availableCopies: 3,
    shelfLocation: "Rack CS-01, Shelf 1",
    publishedYear: 2008,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=400&auto=format&fit=crop&q=80",
    description: "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees.",
    tags: ["Refactoring", "Clean Code", "Design Patterns", "Agile"],
    borrowCount: 84
  },
  {
    _id: "b_2",
    title: "Introduction to Algorithms (CLRS 4th Edition)",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    isbn: "978-0262046305",
    category: "Computer Science",
    subject: "Data Structures & Algorithms",
    totalCopies: 10,
    availableCopies: 5,
    shelfLocation: "Rack CS-01, Shelf 2",
    publishedYear: 2022,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&auto=format&fit=crop&q=80",
    description: "The global benchmark algorithm textbook covering dynamic programming, graph theory, greedy algorithms, and fast Fourier transforms.",
    tags: ["Algorithms", "Data Structures", "Dynamic Programming", "MIT"],
    borrowCount: 120
  },
  {
    _id: "b_3",
    title: "The Pragmatic Programmer: Your Journey to Mastery",
    author: "David Thomas, Andrew Hunt",
    isbn: "978-0135957059",
    category: "Computer Science",
    subject: "Software Engineering & Career",
    totalCopies: 5,
    availableCopies: 2,
    shelfLocation: "Rack CS-01, Shelf 3",
    publishedYear: 2019,
    rating: 4.8,
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80",
    description: "Illustrates the best practices and major pitfalls of modern software development.",
    tags: ["Pragmatic", "Best Practices", "Software Craft"],
    borrowCount: 65
  },
  {
    _id: "b_4",
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    isbn: "978-0201633610",
    category: "Computer Science",
    subject: "Object-Oriented Design",
    totalCopies: 6,
    availableCopies: 4,
    shelfLocation: "Rack CS-02, Shelf 1",
    publishedYear: 1994,
    rating: 4.8,
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&auto=format&fit=crop&q=80",
    description: "The legendary Gang of Four (GoF) handbook presenting 23 classic design patterns.",
    tags: ["Design Patterns", "GoF", "OOP", "Architecture"],
    borrowCount: 72
  },
  {
    _id: "b_9",
    title: "Artificial Intelligence: A Modern Approach (4th Ed)",
    author: "Stuart Russell, Peter Norvig",
    isbn: "978-0134610993",
    category: "Artificial Intelligence",
    subject: "Core Artificial Intelligence",
    totalCopies: 8,
    availableCopies: 0,
    shelfLocation: "Rack AI-01, Shelf 1",
    publishedYear: 2020,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&auto=format&fit=crop&q=80",
    description: "The gold standard AI university textbook covering modern probabilistic agents, reinforcement learning, NLP, and vision.",
    tags: ["AI", "Search Algorithms", "Robotics", "NLP"],
    borrowCount: 95
  },
  {
    _id: "b_10",
    title: "Deep Learning",
    author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
    isbn: "978-0262035613",
    category: "Artificial Intelligence",
    subject: "Deep Learning & Neural Networks",
    totalCopies: 6,
    availableCopies: 2,
    shelfLocation: "Rack AI-01, Shelf 2",
    publishedYear: 2016,
    rating: 4.8,
    coverImage: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80",
    description: "Covers linear algebra, deep feedforward networks, CNNs, sequence modeling, and generative models.",
    tags: ["Deep Learning", "Neural Networks", "PyTorch", "Math"],
    borrowCount: 88
  },
  {
    _id: "b_15",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    isbn: "978-1449373320",
    category: "System Design",
    subject: "Distributed Systems & Databases",
    totalCopies: 8,
    availableCopies: 3,
    shelfLocation: "Rack SYS-01, Shelf 1",
    publishedYear: 2017,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80",
    description: "Comprehensive guide to consistency, partition tolerance, consensus, replication, and batch stream processing.",
    tags: ["System Design", "Distributed Systems", "Databases", "Scalability"],
    borrowCount: 135
  },
  {
    _id: "b_16",
    title: "System Design Interview: An Insider's Guide (Volume 1)",
    author: "Alex Xu",
    isbn: "979-8664653403",
    category: "System Design",
    subject: "High-Scale Architecture & Interviews",
    totalCopies: 8,
    availableCopies: 2,
    shelfLocation: "Rack SYS-01, Shelf 2",
    publishedYear: 2020,
    rating: 4.8,
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&auto=format&fit=crop&q=80",
    description: "Step-by-step solutions for scaling rate limiters, URL shorteners, YouTube video storage, and chat systems.",
    tags: ["System Design", "Scalability", "Microservices", "Alex Xu"],
    borrowCount: 142
  },
  {
    _id: "b_23",
    title: "Kubernetes Up & Running: Dive into Distributed Containers",
    author: "Brendan Burns, Joe Beda, Kelsey Hightower",
    isbn: "978-1098110208",
    category: "Cloud & DevOps",
    subject: "Cloud Native & Orchestration",
    totalCopies: 6,
    availableCopies: 3,
    shelfLocation: "Rack CLOUD-01, Shelf 1",
    publishedYear: 2022,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&auto=format&fit=crop&q=80",
    description: "Written by the original creators of Kubernetes, this book guides you through deploying and managing distributed containers.",
    tags: ["Kubernetes", "Docker", "DevOps", "Cloud Native"],
    borrowCount: 89
  },
  {
    _id: "b_29",
    title: "Python for Data Analysis: Data Wrangling with Pandas and NumPy",
    author: "Wes McKinney",
    isbn: "978-1098104030",
    category: "Data Science",
    subject: "Data Wrangling & Analytics",
    totalCopies: 8,
    availableCopies: 4,
    shelfLocation: "Rack DATA-01, Shelf 1",
    publishedYear: 2022,
    rating: 4.8,
    coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=80",
    description: "Written by the creator of Pandas, master high-performance data manipulation, slicing, and time-series analysis.",
    tags: ["Python", "Pandas", "NumPy", "Data Science"],
    borrowCount: 125
  },
  {
    _id: "b_39",
    title: "Atomic Habits: An Easy & Proven Way to Build Good Habits",
    author: "James Clear",
    isbn: "978-0735211292",
    category: "Productivity",
    subject: "Behavioral Psychology & Focus",
    totalCopies: 8,
    availableCopies: 4,
    shelfLocation: "Rack PROD-01, Shelf 1",
    publishedYear: 2018,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80",
    description: "Practical strategies for forming good habits, breaking bad ones, and mastering tiny behaviors that lead to remarkable results.",
    tags: ["Habits", "Productivity", "Mindset", "Success"],
    borrowCount: 165
  },
  {
    _id: "b_41",
    title: "Cracking the Coding Interview: 189 Programming Questions",
    author: "Gayle Laakmann McDowell",
    isbn: "978-0984782857",
    category: "Computer Science",
    subject: "Software Engineering Career",
    totalCopies: 10,
    availableCopies: 4,
    shelfLocation: "Rack CS-04, Shelf 1",
    publishedYear: 2015,
    rating: 4.9,
    coverImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&auto=format&fit=crop&q=80",
    description: "189 programming interview questions and solutions covering Big-O, arrays, linked lists, trees, DP, and system design.",
    tags: ["Interviews", "Coding", "FAANG", "Algorithms"],
    borrowCount: 190
  }
];

export const initialTransactions = [
  {
    _id: "tx_101",
    studentId: "usr_student_1",
    studentName: "Aarav Sharma",
    studentRoll: "21CS1084",
    bookId: "b_1",
    bookTitle: "Clean Code: A Handbook of Agile Software Craftsmanship",
    bookIsbn: "978-0132350884",
    issueDate: "2026-08-20T10:00:00.000Z",
    dueDate: "2026-09-03T23:59:59.000Z",
    returnDate: null,
    status: "overdue",
    fineAmount: 10,
    finePaid: false,
    issuedBy: "Dr. Albus Vance"
  },
  {
    _id: "tx_102",
    studentId: "usr_student_1",
    studentName: "Aarav Sharma",
    studentRoll: "21CS1084",
    bookId: "b_15",
    bookTitle: "Designing Data-Intensive Applications",
    bookIsbn: "978-1449373320",
    issueDate: "2026-08-28T14:30:00.000Z",
    dueDate: "2026-09-11T23:59:59.000Z",
    returnDate: null,
    status: "issued",
    fineAmount: 0,
    finePaid: true,
    issuedBy: "Dr. Albus Vance"
  }
];

export const initialReservations = [
  {
    _id: "res_201",
    studentId: "usr_student_1",
    studentName: "Aarav Sharma",
    studentRoll: "21CS1084",
    bookId: "b_9",
    bookTitle: "Artificial Intelligence: A Modern Approach (4th Ed)",
    reservedAt: "2026-08-30T15:20:00.000Z",
    status: "waiting",
    queuePosition: 1,
    expiryDate: "2026-09-10T23:59:59.000Z"
  }
];

export const initialNotifications = [
  {
    _id: "notif_301",
    userId: "usr_student_1",
    title: "Overdue Notice: Clean Code",
    message: "Your loan for 'Clean Code' was due on Sep 03, 2026. A nominal overdue fine of ₹10/day is being accrued.",
    type: "warning",
    read: false,
    createdAt: "2026-09-04T08:00:00.000Z"
  }
];
